spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crm_student
    username: javedkhan
    password: javedkhan
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    show-sql: true
